spring:
  cloud:
    sentinel:
      filter:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
swagger:
  exclude-services: consul, service-admin
