server:
  port: 18884
  shutdown: GRACEFUL
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: YAML
        data-key: data
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
