server:
  port: 8883
  shutdown: graceful
spring:
  application:
    name: service-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: YAML
        data-key: data
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
