server:
  port: 18881
  shutdown: graceful
spring:
  application:
    name: service-hi
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: YAML
        data-key: data
    sentinel:
      transport:
        port: 19881
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
